# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='patient',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.Profile'),
        ),
        migrations.AddField(
            model_name='entry',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.Patient'),
        ),
    ]
